name: app_state_examples
description: Examples for app_state Flutter package, a state management solution on top of Router API for larger apps.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  app_state: { path: ../ }
  bloc: ^8.1.0
  enum_map: ^0.1.0
  flutter: { sdk: flutter }
  keyed_collection_widgets: ^0.3.2
  url_launcher: ^6.1.5

#dependency_overrides:
#  enum_map:
#    path: ../../dart-enum-map/enum_map
#  enum_map_gen:
#    path: ../../dart-enum-map/enum_map_gen

dev_dependencies:
  build_runner: ^2.2.0
  enum_map_gen: ^0.1.0
  flutter_lints: ^1.0.0
  flutter_test: { sdk: flutter }

flutter:
  uses-material-design: true
