name: app_state
description: A BLoC-based state management solution on top of Router API for larger apps.
version: 0.6.1
homepage: https://github.com/alexeyinkin/flutter-app-state

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  meta: ^1.7.0
  rxdart: ^0.27.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.21.1
  total_lints: ^2.17.0
