name: app_state
description: A BLoC-based state management solution on top of Router API for larger apps.
version: 0.2.0
homepage: https://github.com/alexeyinkin/flutter-app-state

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  collection: ^1.15.0
  meta: ^1.7.0
  rxdart: ^0.27.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
