name: app_state
description: A state management solution on top of Router API for larger apps.
version: 0.9.6
repository: https://github.com/alexeyinkin/flutter-app-state

topics:
  - state-management
  - navigation
  - routing
  - urls
  - deep-linking

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.16.0
  flutter: { sdk: flutter }
  flutter_issue_108697_workaround: ^0.1.3
  meta: ^1.7.0
  rxdart: ">=0.27.4 <0.29.0"

dev_dependencies:
  build_runner: ^2.4.9
  fake_async: ^1.3.0
  flutter_test: { sdk: flutter }
  mockito: 5.4.4
  test: ^1.25.0
  total_lints: ^3.4.0

#dependency_overrides:
#  total_lints: { path: ../../dart-total-lints }
