name: app_state
description: A state management solution on top of Router API for larger apps.
version: 0.9.4
repository: https://github.com/alexeyinkin/flutter-app-state

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.16.0
  flutter: { sdk: flutter }
  flutter_issue_108697_workaround: ^0.1.3
  meta: ^1.7.0
  rxdart: ^0.27.4

dev_dependencies:
  build_runner: ^2.2.0
  fake_async: ^1.3.0
  flutter_test: { sdk: flutter }
  mockito: 5.4.1
  test: ^1.21.1
  total_lints: ^3.0.0
