name: app_state
description: A state management solution on top of Router API for larger apps.
version: 0.8.2
repository: https://github.com/alexeyinkin/flutter-app-state

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.16.0
  flutter: { sdk: flutter }
  flutter_issue_108697_workaround: ^0.1.2
  meta: ^1.7.0
  rxdart: ^0.27.4

dev_dependencies:
  build_runner: ^2.2.0
  fake_async: ^1.3.0
  flutter_test: { sdk: flutter }
  mockito: 5.2.0 # TODO: Upgrade when fixed: https://stackoverflow.com/a/73253164/11382675
  test: ^1.21.1
  total_lints: ^2.17.3
